swagger: "2.0"
info:
  version: "1.0.0"
  title: Latest Stock Service
  description: Fetch Latest Stock data
host: 'localhost:3000'
basePath: /
tags: 
- name: Stock data 
  description: Stock Data Management
schemes: 
- http
- https
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/getLatestStock:
    post:
      tags:
      - Get Product stock and sku
      # security:
      # - UserSecurity: []
      summary: Get Product Stock
      description: Get Product Stock after some transactions
      produces:
        - application/json
      parameters: 
        - name: sku
          in: path
          description: sku to get latest stock data
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Stock'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
    x-swagger-router-controller: userRoutes
definitions:
  # securityDefinitions:
  #   UserSecurity:
  #     type: apiKey
  #     name: Authorization
  #     in: header
  ErrorResponse:
    type: object
    required:
      - message
    properties:
      message:
        type: string
  Stock:
    type: object
    required:
      - sku
      - stock
    properties:
      sku:
        type: string
      stock:
        type: number